---
version: '3'
services:
  webmonitor:
    image: webmonitor
    container_name: webmonitor
    command: ./src/start_webmonitor.py
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      KAFKA_SECURITY_PROTOCOL:
      KAFKA_SSL_CAFILE:
      KAFKA_SSL_CERTFILE:
      KAFKA_SSL_KEYFILE:

  dbwriter:
    image: webmonitor
    container_name: dbwriter
    command: ./src/start_dbwriter.py
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      KAFKA_SECURITY_PROTOCOL:
      KAFKA_SSL_CAFILE:
      KAFKA_SSL_CERTFILE:
      KAFKA_SSL_KEYFILE:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD:
      DB_SSLMODE: disable
